export const REGISTER_ALUNO_REQUEST = 'REGISTER_ALUNO_REQUEST'
export const REGISTER_ALUNO_SUCCESS = 'REGITER_ALUNO_SUCCESS'
export const REGISTER_ALUNO_FAILURE = 'REGISTER_ALUNO_FAILURE'

export const FETCH_ALUNO_REQUEST = 'FETCH_ALUNO_REQUEST'
export const FETCH_ALUNO_SUCCESS = 'FETCH_ALUNO_SUCCESS'
export const FETCH_ALUNO_FAILURE = 'FETCH_ALUNO_FAILURE'
