export const REGISTER_ALUNO_REQUEST = 'REGISTER_ALUNO_REQUEST'
export const REGISTER_ALUNO_SUCCESS = 'REGITER_ALUNO_SUCCESS'
export const REGISTER_ALUNO_FAILURE = 'REGISTER_ALUNO_FAILURE'

export const REGISTER_PROFESSOR_REQUEST = 'REGISTER_PROFESSOR_REQUEST'
export const REGISTER_PROFESSOR_SUCCESS = 'REGISTER_PROFESSOR_SUCCESS'
export const REGISTER_PROFESSOR_FAILURE = 'REGISTER_PROFESSOR_FAILURE'

export const FETCH_ALUNO_REQUEST = 'FETCH_ALUNO_REQUEST'
export const FETCH_ALUNO_SUCCESS = 'FETCH_ALUNO_SUCCESS'
export const FETCH_ALUNO_FAILURE = 'FETCH_ALUNO_FAILURE'

export const DELETE_ALUNO_REQUEST = 'DELETE_ALUNO_REQUEST'
export const DELETE_ALUNO_SUCCESS = 'DELETE_ALUNO_SUCCESS'
export const DELETE_ALUNO_FAILURE = 'DELETE_ALUNO_FAILURE'
